// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFuwpPuak1q9ybly-Z8DQwCFomzKU_Wo',
    appId: '1:851553929163:web:462311cae6bcca08ccd84e',
    messagingSenderId: '851553929163',
    projectId: 'gatheruni-58fa7',
    authDomain: 'gatheruni-58fa7.firebaseapp.com',
    storageBucket: 'gatheruni-58fa7.firebasestorage.app',
    measurementId: 'G-0SE1NYPMJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zunZn4wupxtP-WKmyCm4X6HLus12LUg',
    appId: '1:851553929163:android:bb3fe3bd0ee1d4f9ccd84e',
    messagingSenderId: '851553929163',
    projectId: 'gatheruni-58fa7',
    storageBucket: 'gatheruni-58fa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNO4K3ukXuzXf1b-qXiAxJ4EGR1L4UCM',
    appId: '1:851553929163:ios:62fefede43af5b27ccd84e',
    messagingSenderId: '851553929163',
    projectId: 'gatheruni-58fa7',
    storageBucket: 'gatheruni-58fa7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNO4K3ukXuzXf1b-qXiAxJ4EGR1L4UCM',
    appId: '1:851553929163:ios:62fefede43af5b27ccd84e',
    messagingSenderId: '851553929163',
    projectId: 'gatheruni-58fa7',
    storageBucket: 'gatheruni-58fa7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuFuwpPuak1q9ybly-Z8DQwCFomzKU_Wo',
    appId: '1:851553929163:web:c416ff806028dc67ccd84e',
    messagingSenderId: '851553929163',
    projectId: 'gatheruni-58fa7',
    authDomain: 'gatheruni-58fa7.firebaseapp.com',
    storageBucket: 'gatheruni-58fa7.firebasestorage.app',
    measurementId: 'G-HN68WQY2GK',
  );
}
